name:                quad-solver
version:             0.1.0.0
github:              "ruzen42/quad-solver"
license:             BSD-3-Clause
author:              "Jaroslav Mihajlenko"
maintainer:          "malledeferlive@gmail.com"
copyright:           BSD-3-Clause

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Simple quad equation solver
category:            Science

description:         Please see the README on GitHub at <https://github.com/ruzen42/quad-solver#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  quad-solver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quad-solver

tests:
  quad-solver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quad-solver
    - HUnit
